---
- name: "{{ 'Determine the ' + item.user + ' user home directory' }}"
  ansible.builtin.stat:
    path: "~"
  register: home
  become: true
  become_user: "{{ item.user }}"

- name: "Ensure .ssh directory exists for {{ item.user }}"
  ansible.builtin.file:
    path: "{{ home.stat.path }}/.ssh"
    state: directory
    owner: "{{ home.stat.uid }}"
    group: "{{ home.stat.gid }}"
    mode: "0700"

- name: "Ensure SSH include directory exists for {{ item.user }}"
  ansible.builtin.file:
    path: "{{ home.stat.path }}/.ssh/conf.d"
    state: directory
    owner: "{{ home.stat.uid }}"
    group: "{{ home.stat.gid }}"
    mode: "0755"

- name: "Ensure SSH configuration file exists for {{ item.user }}"
  ansible.builtin.copy:
    content: |
      Include ~/.ssh/conf.d/*
    dest: "{{ home.stat.path }}/.ssh/config"
    force: false
    owner: "{{ home.stat.uid }}"
    group: "{{ home.stat.gid }}"
    mode: "0644"

- name: "Ensure SSH include directory is used for {{ item.user }}"
  ansible.builtin.lineinfile:
    dest: "{{ home.stat.path }}/.ssh/config"
    regexp: "^Include ~/.ssh/conf.d/*"
    line: "Include ~/.ssh/conf.d/*"
    state: present
    owner: "{{ home.stat.uid }}"
    group: "{{ home.stat.gid }}"
    mode: "0644"

- name: "{{ 'Creating local SSH config files for ' + item.user + ' and ' + item.host }}"
  ansible.builtin.template:
    src: templates/ssh_config.j2
    dest: "{{ home.stat.path }}/.ssh/conf.d/{{ item.host }}"
    owner: "{{ home.stat.uid }}"
    group: "{{ home.stat.gid }}"
    mode: "0644"
